### ISSUE TITLE
Add Vega and Polaris Series Drivers

### ISSUE THREAD

**Issue by xrgzs** [nunodxxd/AMD-Software-Adrenalin#2]
Please add drivers for Vega and Polaris Series. They are supporting AMD Software: Adrenalin Edition driver but do not appear in this repository.

https://www.amd.com/en/support/downloads/drivers.html/graphics/radeon-600-500-400/radeon-rx-500-series/radeon-rx-580.html

https://drivers.amd.com/drivers/whql-amd-software-adrenalin-edition-24.9.1-win10-win11-vega-polaris.exe

There is a combined version in release notes.

https://www.amd.com/en/resources/support-articles/release-notes/RN-RAD-WIN-24-10-1.html

https://drivers.amd.com/drivers/whql-amd-software-adrenalin-edition-24.10.1-win10-win11-oct-rdna-combined.exe

**Comment by nunodxxd** [comment]
The next release will include the combined version, if available.

**Comment by xrgzs** [comment]
Thank you very much, my maintenance tools can't access the AMD website smoothly, this repository is useful for me.
